include(../../plugins/projectexplorer/projectexplorer.pri)
include(../../plugins/texteditor/texteditor.pri)
include(../../plugins/pythoneditor/pythoneditor.pri)
include(../../plugins/debugger/debugger.pri)
include(../../plugins/qtsupport/qtsupport.pri)
